// Array of Objects containing data related to depicted charactes on lineage tree
const meritObjects = [{
    firstName: "Padmasambhava",
    aka: "",
    birth: "8. century",
    death: "8. century",
    lineage: "",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "short bio",
    prediction: "",
    img: "./img/santaraksita.jpg"
  },
  {
    firstName: "Shantarakshita",
    aka: "",
    birth: "725",
    death: "788",
    lineage: "",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "short bio",
    prediction: "",
    img: "./img/santaraksita.jpg"
    // https://en.wikipedia.org/wiki/%C5%9A%C4%81ntarak%E1%B9%A3ita
  },
  {
    firstName: "Padampa Sanjay",
    aka: "Father Excellent Buddhahood",
    birth: "around 1117",
    death: "around 1117",
    lineage: "",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "short bio",
    prediction: "",
    img: "./img/dampa_sangye.jpg"
    // https://en.wikipedia.org/wiki/Dampa_Sangye
  },
  {
    firstName: "King Trisung Detsun",
    aka: "",
    birth: "755",
    death: "804",
    lineage: "",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "short bio",
    prediction: "",
    img: "./img/Trisong_Detsen.jpg"
  },
  {
    firstName: "Longchenpa",
    aka: "",
    birth: "1308",
    death: "1364",
    lineage: "Nyingma",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "short bio",
    prediction: "",
    img: "./img/Longchenpa.jpg"
  },
  {
    firstName: "Dolpopa",
    aka: "",
    birth: "1292",
    death: "1361",
    lineage: "Principal exponent shentong teachings. Influential member of Jonang tradition",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "<strong>Künkhyen Dölpopa Sherab Gyeltshen</strong> (tib. kun mkhyen dol po pa shes rab rgyal mtshan; * 1292; † 1361) oder kurz Dölpopa war ein bedeutender Lama der Jonang-Tradition des tibetischen Buddhismus und Philosoph. Dölpopa war ein Schüler von Künpang Thugje Tsöndrü (kun spangs thugs rje brtson 'grus; 1243–1313), des Gründers des Jonang-Klosters. Unter Dölpopas Einfluss bildete sich die Jonang-Tradition (jo nang pa) im 14. Jahrhundert zu einer eigenständigen Schule des tibetischen Buddhismus. Er war Mönch des Sakya - Klosters und später des Jonang - Klosters.Er war ein Kalachakra - Spezialist und formulierte die Lehre vom Shentong(tib.: gzhan stong) als erster schriftlich aus,insbesondere in seinem Werk Ri chos nges don rgya mtsho(ri chos).Er wird auch als der Buddha von Dolpo(Dol po 'i Sangs rgyas) bezeichnet.",
    prediction: "",
    img: "./img/dolpopa.jpg"
  },
  {
    firstName: "Tilopa",
    aka: "",
    birth: "988",
    death: "1069",
    lineage: "Six Precepts or Words of Advice",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "Tilopa - ausgezeicnnets Wissen",
    bio: "short bio",
    prediction: "",
    img: "./img/tilopa.jpg"
  },
  {
    firstName: "Naropa",
    aka: "",
    birth: "",
    death: "",
    lineage: "",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    // "Prayer" key refers to occurence in mahamudra lineage Prayer
    prayer: "Jnana Siddhi(errungene Urbewusstheit)",
    bio: "short bio",
    prediction: "",
    img: "./img/naropa.jpg"
  },
  {
    firstName: "Saraha",
    aka: "",
    birth: "8th century",
    death: "",
    lineage: "One of the founders of Buddhist Vajrayana, and particularly of the Mahamudra tradition",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Kurze Bio",
    prediction: "",
    img: "./img/saraha.jpg"
  },
  {
    firstName: "Marpa",
    aka: "",
    birth: "1012",
    death: "1097",
    lineage: "",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "Dharma Intelligenz",
    bio: "Kurze Bio",
    prediction: "",
    img: "./img/marpa.jpg"
  },
  {
    firstName: "Milarepa",
    aka: "",
    birth: "1028",
    death: "1111",
    lineage: "",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "Lachender Vajra",
    bio: "Short Bio",
    prediction: "",
    img: "./img/milarepa.jpg"
  },
  {
    firstName: "Drogon Rechen",
    aka: "Sonam Dragpa",
    birth: "1204",
    death: "1283",
    lineage: "",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Short Bio",
    prediction: "",
    img: "./img/drogon_rechen.jpg"
  },
  {
    firstName: "Tsongkhapa",
    aka: "The Man from Onion Valley",
    birth: "1357",
    death: "1419",
    lineage: "His teachings lead to formation of the Gelug School",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Kurze Bio",
    prediction: "It is said that the Buddha Sakyamuni spoke of his coming as an emanation of the Bodhisattva Manjusri in the short verse from the Root Tantra of Manjushri",
    img: "./img/tsongkhapa.jpg"
  },
  {
    firstName: "Sachen Kunga Nyingpo",
    aka: "",
    birth: "1092",
    death: "1158",
    lineage: "First of the Five Venerable Supreme Sakya Masters of Tibet",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "At the age of twelve, Sachen, under the guidance of his guru, Bari Lotsava, performed one-point meditation on Manjushri. After meditating on this for a continuous period of six months, the bodhisattva appeared in front of him and gave him the teachings on the parting of four attachments. Sachen realised in an instant that this teaching contained the essence of the Path of Perfection.He was a strict vegetarian and received teachings and empowerments on sutras and tantras from many great teachers",
    Prediction: "",
    img: "./img/sachen_kunga_nyingpo.jpg"
  },
  // Need to ask: https://www.bodhicittasangha.org/100-syllable-mantra/
  {
    firstName: "Prajnaparamita",
    aka: "",
    birth: "",
    death: "",
    lineage: "",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: 'Prajñāpāramitā means "the Perfection of (Transcendent) Wisdom" in Mahāyāna Buddhism. Prajñāpāramitā refers to this perfected way of seeing the nature of reality, as well as to a particular body of sutras and to the personification of the concept in the Bodhisattva known as the "Great Mother" (Tibetan: Yum Chenmo). The word Prajñāpāramitā combines the Sanskrit words prajñā "wisdom" with pāramitā "perfection". Prajñāpāramitā is a central concept in Mahāyāna Buddhism and is generally associated with the doctrine of emptiness (Shunyata) or \'lack of Svabhava\' (essence) and the works of Nagarjuna. Its practice and understanding are taken to be indispensable elements of the Bodhisattva path.',
    prediction: "",
    img: "./img/prajnaparamita.jpg"
  },
  {
    firstName: "Vajrasattva",
    aka: "",
    birth: "",
    death: "",
    lineage: "",
    work: "",
    mantra: "100 Syllable Mantra",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "In Tibetan Buddhism Vajrasatva is associated with the\nsambhogakāya and purification practice.\nVajrasatva appears principally in two Buddhists texts: the Mahavairocana Sutra and the Vajrasekhara Sutra.In the Diamond Realm Mandala,Vajrasatva sits to the East near Akshobhya Buddha. In some esoteric lineages,Nagarjuna was said to have met Vajrasatva in an iron tower in South India, and was taught tantra, thus transmitting the esoteric teachings to more historical figures ",
    prediction: "",
    img: "./img/prajnaparamita.jpg"
  },
  {
    firstName: "Samanthabadra",
    aka: "",
    birth: "",
    death: "",
    lineage: "",
    work: "",
    mantra: "100 Syllable Mantra",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Samantabhadra Skt.; Tib. ཀུན་ཏུ་བཟང་པོ་ Kuntu Zangpo Wyl. kun tu bzang po — In the Dzogchen teachings, our true nature, that state of the Ground, is given the name the 'Primordial Buddha'.",
    prediction: "",
    img: ""
  },
  {
    firstName: "Vajradhara",
    aka: "",
    birth: "",
    death: "",
    lineage: "",
    work: "",
    mantra: "100 Syllable Mantra",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Vajradhāra (Sanskrit: वज्रधर. Also, the name of Indra, because 'Vajra' means diamond, as well as the thunderbolt, anything hard more generally) Tibetan: རྡོ་རྗེ་འཆང། rdo rje 'chang (Dorje Chang); is the ultimate primordial Buddha, or Adi Buddha, according to the Sakya[1], Gelug and Kagyu schools of Tibetan Buddhism.\nIn the evolution of Indian Buddhism, Buddha Vajradhāra gradually displaced Samantabhadra, who is the 'Primordial Buddha' in the Nyingma, or 'Ancient School.' However, the two are metaphysically equivalent. Achieving the 'state of Vajradhāra' is synonymous with complete realisation.\nAccording to the Kagyu lineage, Buddhā Vajradhāra is the primordial Buddha, the Dharmakaya Buddha.He is depicted as dark blue in color, expressing the quintessence of buddhahood itself and representing the essence of the historical Buddha 's realization of enlightenment",
    prediction: "",
    img: "./img/vajradhara.jpg"
  },
  {
    firstName: "Atisha",
    aka: "",
    birth: "982",
    death: "1054",
    lineage: "Kadampa",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "He was one of the major figures in the spread of 11th-century Mahayana and Vajrayana Buddhism in Asia and inspired Buddhist thought from Tibet to Sumatra. In 1013, he travelled to the kingdom of Srivijaya and stayed there for 12 years before returning to India. He is recognised as one of the greatest figures of classical Buddhism. Atiśa's chief disciple, Dromtön, was the founder of the Kadam school, one of the New Translation schools of Tibetan Buddhism, later supplanted by the Gelug tradition in the 14th century, adopting its teachings and absorbing its monasteries.[4] In 2004, Atiśa was ranked 18th in the BBC's poll of the greatest Bengalis of all time.",
    prediction: "",
    img: "./img/atisha.jpg"
  },
  {
    firstName: "Jikten Sumgon",
    aka: "Jigten Gönpo",
    birth: "982",
    death: "1054",
    lineage: "Driklung Kagyu",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Jigten Sumgön and the Drikung lineage are best known for the set of teachings known as The Five Profound Paths of Mahāmudrā (phyag chen lnga ldan).",
    prediction: "",
    img: "./img/jiktun_sumgon.jpg"
  },
  // https://treasuryoflives.org/biographies/view/Lingrepa-Pema-Dorje/11877
  {
    firstName: "Ling Repa",
    aka: "",
    birth: "1128",
    death: "1188",
    lineage: "Driklung Kagyu",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Lingrepa Pema Dorje (gling ras pa pad+ma rdo rje) was born in 1128, in upper Nyang (smyang stod), the general area that includes the city of Gyantse (rgyal rtse) in south-central Tibet. His father, a member of the Lingme family (gling smad) was an expert in tantra who earned his living as a doctor and astrologer. When he was seven a field was sold to pay for his apprenticeship to a doctor named Ramen (ra sman). His medical studies were going well when at age twelve, his father died. At age sixteen he took novice vows, and he studied, among other things, the Six Lamps (sgron ma drug) of Pelyang (dpal dbyangs). Later Lingrepa would write his own Six Lamps under the inspiration of these Nyingma texts.",
    prediction: "",
    img: "./img/Ling_Repa.jpg"
  },
  {
    firstName: "Phakmo Drugpa",
    aka: "",
    birth: "1110",
    death: "1170",
    lineage: "Nyingma",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Phagmo Drupa Dorje Gyalpo (Tibetan: ཕག་མོ་གྲུ་པ་རྡོ་རྗེ་རྒྱལ་པོ, Wylie: phag mo gru pa rdo rje rgyal po) [1110-1170], was one of the three main disciples of Gampopa Sonam Rinchen who established the Dagpo Kagyu school of Tibetan Buddhism; and a disciple of Sachen Kunga Nyingpo [1092-1158] one of the founders of the Sakya school of Tibetan Buddhism. He was the elder brother of Kathog Dampa Deshek [1122-1192], who founded Kathog monastery and the Kathog branch of the Nyingma school.",
    prediction: "",
    img: "./img/Phakmo_Drukpa.jpg"
  },
  {
    firstName: "Jamyang Chentze",
    aka: "IS THIS THE CORRECT INFORMATION?????",
    birth: "",
    death: "",
    lineage: "Nyingma",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Jamyang Khyentsé Wangpo (Tib. འཇམ་དབྱངས་མཁྱེན་བརྩེའི་དབང་པོ་, Wyl. 'jam dbyangs mkhyen brtse'i dbang po) (1820-1892), also known as Pema Ösal Do-ngak Lingpa (Tib. པདྨ་འོད་གསལ་མདོ་སྔགས་གླིང་པ་, Wyl. pad+ma 'od gsal mdo sngags gling pa) was a major treasure revealer—the last of the Five Sovereign Tertöns—and one of the most eminent masters of the nineteenth century. He was a contemporary of Chokgyur Lingpa (1829-1870) and Jamgön Kongtrul the Great and was regarded as the combined reincarnation of Vimalamitra and King Trisong Deutsen. He became the founder of the Rimé (ecumenical) movement. ",
    prediction: "",
    img: "./img/jamyang_chentze.jpg"
  },
  {
    firstName: "Saltong Shogom",
    aka: "",
    birth: "around 12th century",
    death: "around 12th century",
    lineage: "Karma Kagyu / Founder of an own sect which is vanished now",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Saltong Shogom (Tib. གསལ་སྟོང་ཤྭོ་སྒོམ་, Wyl. gsal stong shwo sgom) (b. 12th century), one of the main disciples of Gampopa. He was the founder of a minor Kagyü sub-school that has since disappeared",
    prediction: "",
    img: "./img/saltong_shogom.jpg"
  },
  // http:zurmangkagyu.org/the-first-zurmang-gharwang/
  {
    firstName: "Trung Mase",
    aka: "The First Zurmang Gharwang",
    birth: "1384",
    death: "1425",
    lineage: "Zurmang Kagyu",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "The earliest manifestation of the glorious Lord of Refuge known as Zurmang Gharwang can be traced as far back as the 14th century, to the time of the Fifth Gyalwa Karmapa, Deshing Shegpa (1384-1425).",
    prediction: "",
    img: "./img/trung_mase.jpg"
  },
  {
    firstName: "Khyungpo Natjor",
    aka: "",
    birth: "",
    death: "",
    lineage: "",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "SORRY, NO INFORMATIONS AVAILABLE",
    prediction: "",
    img: " "
  },
  {
    firstName: "Nagarjuna",
    aka: "",
    birth: "150",
    death: "250",
    lineage: "Founder of Madhyamaka",
    work: "Mūlamadhyamakakārikā",
    mantra: "OM MARA PAT SA NADI ????",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: 'According to some accounts, Nāgārjuna was originally from South India.[1][5] Some scholars believe that Nāgārjuna was an advisor to a king of the Satavahana dynasty.[1] Archaeological evidence at Amarāvatī indicates that if this is true, the king may have been Yajña Śrī Śātakarṇi, who ruled between 167 and 196 CE. According to a 4th/5th-century biography translated by Kumārajīva, Nāgārjuna was born into a Brahmin family[6] in Vidarbha[7][8][9] (a region of Maharashtra) and later became a Buddhist. Some sources claim that in his later years, Nāgārjuna lived on the mountain of Śrīparvata near the city that would later be called Nāgārjunakoṇḍa "Hill of Nāgārjuna") The name "Nagarjunakonda"  dates from the medieval period, and the 3rd-4th century inscriptions found at the site make it clear that it was known as "Vijayapuri" in the ancient period.\'',
    prediction: "",
    img: "./img/nagarjuna.jpg"
  },
  // http://www.druponrinpoche.org/en/lineage/kagyu-lineage/ratnamati/
  {
    firstName: "Ratnamati",
    aka: "",
    birth: "",
    death: "",
    lineage: "Mahamudra",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Ratnamati or Lodrö Rinchen (in Tibetan) is a bodhisattva emanation of the Dharmakaya Buddha Vajradhara. Together with the Bodhisattva Sukhanatha, (an emanation of Vajrapani), he is responsible for bringing the Mahamudra teachings into our human world. They transmitted the teachings of Mahamudra to the Indian Mahasiddha Saraha, who in turn passed them on to his human disciples. It passed from him to Nagarjuna, Savaripa and then to Maitripa. This is one of the two Mahamudra lineages which Marpa Lotsawa received in India and brought back to Tibet.",
    prediction: "",
    img: "./img/ratnamati.jpg"
  },
  // https:ganachakra.com/tag/mahamudra-2/
  // Auch sehr cooles BLOG
  {
    firstName: "Shawaripa",
    aka: "",
    birth: "",
    death: "",

    lineage: "Mahamudra & Indian Patriarch of the Kagyü lineage",
    work: " ",
    mantra: "",
    disciple: "Maitripa",
    teacher: "Nagarjuna",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Shavaripa (Skt. Śāvaripa; Tib. ཤ་བ་རི་པ་ or རི་ཁྲོད་དབང་ཕྱུག, Wyl. sha ba ri pa or ri khrod dbang phyug), the 'Hunter' — one of the eighty-four mahasiddhas of India. Shavaripa was a hunter who turned to the Buddhist path and renounced his livelihood after an encounter with the bodhisattva Avalokiteshvara. He later became a disciple of Nagarjuna and a teacher of Maitripa. Shavaripa is a key figure in the transmission of the early Mahamudra lineage of teachings in India, and counted among the 'Indian Patriarchs' of the Kagyü lineage. DISCIPLE OFnagarjuna   TEACHER OFmaitripa",
    prediction: "",
    img: "./img/shawaripa.jpg"
  },
  {
    firstName: "Maitripa",
    aka: "Maitrīgupta, Advayavajra",
    birth: "1007",
    death: "1085",
    lineage: "Mahamudra Kagyü",
    work: "",
    mantra: "",
    disciple: "Atisha, Marpa, Vajrapani, Karopa, Natekara, Devākaracandra, Rāmapāla",
    teacher: "<h2>Teacher:</h2> Shavaripa, Naropa",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Maitrīpadā (c. 1007–1085, also known as Maitrīgupta, Advayavajra, and, to Tibetans, Maitrīpa), was a prominent Indian Buddhist Mahasiddha associated with the Mahāmudrā transmission.[1] His teachers were Shavaripa and Naropa.[1] His students include Atisha, Marpa, Vajrapani, Karopa, Natekara (also known as Sahajavajra), Devākaracandra (also known as Śūnyatāsamādhi), and Rāmapāla.[1] His hermitage was Mithilā (also known as Tirhut), somewhere in northern Bihar and neighboring parts of southern Nepal.[1] He was influential as the major source of the teachings of mahamudra for Tibetan Buddhism.",
    // Teachings:
    //   "Maitrīpāda composed commentaries on the buddhist dohas of Saraha. His most important works are a collection of 26 texts on \"non - conceptual realization\" (amanasikara), which are a key Indian source of mahāmudrā in the Tibetan tradition. These works teach a synthesis of Buddhist Mahayana teachings on emptiness and 'non-abiding' (apratisthana) and Buddhist tantric practices, and they also teach an instantanious path to awakening",
    prediction: "",
    img: "./img/maitripa.jpg"
  },
  {
    firstName: "Dusum Khyenpa",
    aka: "",
    birth: "1110",
    death: "1193",
    lineage: "1st Karmapa",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "",
    prediction: "",
    img: ""
  },
  {
    firstName: "Rangjung Dorje",
    aka: "",
    birth: "1284",
    death: "1339",
    lineage: "3rd Karmapa Lama",
    work: "Aspiration Prayer of Mahamudra, Prayer to the Lineage of Chö, Distinguishing Consciousness from Wisdom, Instructions on Sahajayoga Mahamudra, A Treatise on Buddha Nature",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Rangjung Dorje visited China, where the emperor Toghon Temur became his disciple. Upon his death, Rangjung Dorje's face is said to have appeared in the moon there. As a group, the Karmapa Lamas were among the earliest recognized Tulku, or lamas reincarnated as deities or lineage of deceased teachers. The first Karmapas were influential in the Yuan and Ming courts as well as the Tangut Western Xia Kingdom. In 1321 the famous scholar Dolpopa (1292-1361) visited Tsurphu Monastery for the first time and had extensive discussions with Rangjung Dorje about doctrinal issues. It appears that Rangjung Dorje almost certainly influenced the development of some of Dolpopa's theories, possibly including his Zhentong (gzhan stong) method. According to Karma phrin las, Dri lan yid, 91 - 92, his teacher, Chödrak Gyatso, the Seventh Karmapa, interpreted the nature of Zhentong(gzhan stong) accepted by Rangjung Dorje ",
    prediction: "",
    img: "./img/karmapa3.jpg"
  },
  {
    firstName: "Gampopa",
    aka: "The Physician from Gampo",
    birth: "1079",
    death: "1153",
    lineage: "Belongs to the five founding Masters of Kagyü School",
    work: "Jewel Ornament of Liberation",
    mantra: "",
    disciple: "",
    teacher: "Milarepa",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Gampopa was born in the Nyal (or Nyel) district, Central Tibet and from an early age was a student of medicine in the Indian, Chinese and Tibetan medical traditions.[3] Later in his life he moved to the region of Dakpo (dwags po) in southern Tibet and hence was also called Dakpopa (dwags po pa), the man from Dakpo. The region is also near Gampo Hills, hence his other name, Gampopa.[4] In his youth Gampopa studied under the Nyingma lama Barey as well as under the Kadampa teacher Geshe Yontan Drag.[5] He married a daughter of a man named Chim Jose Darma Wo (mchims jo sras dar ma 'od) and had a child, but they both died, causing him to renounce the householder's life. In 1104, at the age of twenty-five he took ordination, either in Dakpo or in Penyul, at Gyachak Ri monastery ('phan yul rgya lcags ri), receiving the name Sönam Rinchen (bsod nams rin chen).n\"After becoming a monk in the Kadampa lineage under Geshe Lodan Sherab and focused on studying the Kadampa teachings. [7] In his 30 s he sought out and became the foremost student of the yogi Milarepa. [8] Milarepa instructed him in the practice of Vajravārahī, tummo(gtum mo) and Mahāmudrā",
    prediction: "",
    img: "./img/gampopa.png"
  },
  {
    // https://en.wikipedia.org/wiki/Deshin_Shekpa,_5th_Karmapa_Lama
    firstName: "Dezhin Shekpa",
    aka: "",
    birth: "1384",
    death: "1415",
    lineage: "The fifth Karmapa",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "",
    prediction: "",
    img: "./img/karmapa5.jpg"
  },
  {
    //www.druponrinpoche.org/en/lineage/kagyu-lineage/drogon-rechen/

    // https://www.palpung.org/english/lineage/tai_14.htm
    firstName: "Drogon Rechen",
    aka: "",
    birth: "1148",
    death: "1218",
    lineage: "",
    work: "",
    mantra: "",
    disciple: "Pomdrakpa Sönam Dorje",
    teacher: "Dusum Khyenpa",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Drogon Rechen was born to a prosperous family in the Yarlung area of Tsang in southern Central Tibet. He gave rise to bodhicitta while only a child and, by the age of nine, he became a student of the Kagyu siddha Zangri Repa. He received many teachings from this lama, including the ear-whispered instructions and dohas of the Mahamudra masters. He practiced meditation wearing only a cotton cloth and experienced many signs of meditative accomplishment, which earned him the name Rechen, ‘great cotton-clad yogi’. Zangri Repa passed into Parinirvana when Drogon Rechen was fifteen.Before he died, his Lama advised Drogon Rechen to find the disciples of Milarepa’ s lineage, saying he should receive the full lineage transmission, and practice hard so that he could become a great master.In the following years he studied and practiced under many Kagyu and Nyingma masters and although he attained great qualities of samadhi, he still was not full satisfied.Deciding to leave his home to develop his practice further,he set off on the journey to Kham, in eastern Tibet.During this time he met and trained under a number of different masters: from Thöpa Samdrup he received the transmission of the Chöd lineage; Ngaripa bestowed the Vajrapani and Vajrasadhu transmissions; and Nyalpa Josey gave him the Peaceful and Wrathful Manjushri and Mahakala practices.He also received the Dzogchen transmission of the Vima Nyingthig.Showing signs of having mastered the practices of prana, nadi and bindu, he began to be a little proud of his accomplishments.While travelling, he was listening to the conversation of some fellow pilgrims one evening when he heard them respectfully discussing the accomplishments and activities of the great Dusum Khyenpa.Overcome, Drogon Rechen immediately knew, ‘He is my Lama.I have a karmic connection with him from many past lives.I will do everything to find him.’ Learning that Dusum Khyenpa was living at Kampo Nenang, Drogon Rechen set off to meet him.Dusum Khyenpa did not make it easy for Drogon Rechen, and put him though a few tests first. Making a strong commitment, he practiced under the direction of Dusum Khyenpa’ s students for seven years and completely stabilised his practice and realisation. Drogon Rechen also became a fully ordained monk at the age of thirty - seven and was given the name Sonam Dragpa.He continued to receive the full Kagyu transmission from Dusum Khyenpa for three more years, upon which he became the lineage holder.When Dusum Khyenpa travelled back to Central Tibet, Drogon Rechen stayed in Kham, carrying out the activities of his root guru at Karma Gön and Khampo Nyenang.At the age of seventy,Drogon Rechen passed into Parinirvana, leaving behind many relics after his cremation.His principal disciple and the Kagyu lineage holder was Pomdrakpa Sonam Dorje.",
    prediction: "",
    img: "./img/Drogon-Rechen.jpg"
  },
  {
    //www.druponrinpoche.org/en/lineage/kagyu-lineage/drogon-rechen/

    // https://www.rigpawiki.org/index.php?title=Orgyenpa_Rinchen_Pal
    firstName: "Urgyenpa Rinchenpal",
    aka: "",
    birth: "1230",
    death: "1309",
    lineage: "",
    work: "",
    mantra: "",
    disciple: "Karmapa Rangjung Dorje | Third Karmapa",
    teacher: "Götsangpa Gönpo Dorje Karma Pakshi",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "",
    prediction: "",
    img: "./img/Orgyenpa-Rinchen-Pal.jpg"
  },
  {
    // https://www.palpung.org/english/mahamudra/refugetreemaster/default.asp?thepagename=20_ratnabhadra
    firstName: "Ratnabhadra",
    aka: "Rigowa Rinjung",
    birth: "14th Century",
    death: "",
    lineage: "",
    work: "",
    mantra: "",
    disciple: "6th Gyalwa Karmapa",
    teacher: "5th Karmapa Deshin Shekpa",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Rigowa Rinjung(ratnabhadra) was born into the well - known family of Soksam in the 14 th Century CE.He was considered to be an emanation of the Kenting Tai Situpa. At a young age, Ratnabhadra was ordained as a monk.He received higher training in Buddhist philosophy, logic, and other fields of knowledge at Palden Sangphu college. Situ Ratnabhadra then visited the great monastic institutions in Tibet, engaging in debate and discussion on the four main topics of Madhyamika, Prajnaparamita, Vinaya, and Abhidharma.He became one of the greatest scholars of sutra and tantra and thus was called Rigpe Raltri(sword of philosophy and logic). He received the full transmission of the Kagyu lineage from the 5 th Karmapa Deshin Shekpa, through which he attained complete realization.He became one of the supreme meditation masters of the time. Ratnabhadra was also the lineage holder and a teacher to the 6th Gyalwa Karmapa.",
    prediction: "",
    img: "./img/ratnabhadra.jpg"
  },
  {
    // https://en.wikipedia.org/wiki/Ch%C3%B6drak_Gyatso,_7th_Karmapa_Lama
    firstName: "Chodrak Gyamtso",
    aka: "",
    birth: "1454",
    death: "1506",
    lineage: "Seventh Karmapa",
    work: "Ocean Of Logic, Lamp of the Three Worlds",
    mantra: "",
    disciple: "",
    teacher: "Dri lan yid",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Short bio placeholder",
    // 'Chödrak Gyatso, also Chödrag Gyamtso, was the seventh Karmapa, head of the Kagyu School of Tibetan Buddhism. Chödrak Gyatso was born in Chida in the north of Tibet.According to the legend, he said at the age of five months: "There is nothing on this world, except for emptiness." He was recognized as Karmapa at the age of nine months. According to the legend he established peace at the age of five during a tour through Tibet where in the south the tribes of Nagaland and Bhutan were engaged in a war. He spent a large part of his life protecting animals and teaching people to give up hunting and fishing.His main activities were to prevent and solve conflicts between the tribes and building bridges and roads to connect the different areas.Chödrak send a lot of gold to India to enable the gilding of the statue of the Gautama Buddha near Bodh Gaya. According to Karma phrin las, Dri lan yid, his teacher  Chödrak Gyatso, interpreted the nature of shentong accepted by Rangjung Dorje 3 rd Karmapa Lama, who, in turn, had probably influenced and been influenced by the great shentong master Dolpopa Sherab Gyaltsen.He was also accomplished scholar, most famous for authoring the Ocean Of Logic, which is considered the most important text on pramana in the Kagyu tradition. He also authored an important commentary on Asangas Abhisamayalankara called Lamp of the Three Worlds.',
    prediction: "",
    img: "./img/chodrak_gyamtso.jpg"
  },
  {
    firstName: "Yungtompa",
    aka: "",
    birth: "",
    death: "",
    lineage: "",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "",
    prediction: "",
    img: ""
  },
  {
    // https://treasuryoflives.org/biographies/view/Pomdrakpa-Sonam-Dorje/4140
    firstName: "Pomdrakpa",
    aka: "Pomdrakpa Sonam Dorje",
    birth: "1170",
    death: "1249",
    lineage: "",
    work: "",
    mantra: "",
    disciple: "",
    teacher: "Drogon Rechen, Sanggye Rechen Peldrak, Tsangton Dorje Gyeltsen",
    quote: "",
    contemporaries: "",
    prayer: "",
    bio: "Short bio placeholder",
    // "Pomdrakpa Sonam Dorje (spom brag pa bsod nams rdo rje) was born in 1170 in Drigyel Dampa Chopuk ('bri rgyal dam pa chos phyug). According to the Blue Annals, he mastered reading at writing at age five, and at the age of nine he received transmissions in Cakrasaṃvara and Hevajra from a father and son pair known as Lama Nyen Lhakhang Gangwa (bla ma gnyan lha khang sgang ba, d.u.). When he was fourteen Sonam Dorje met Sanggye Rechen Peldrak (sangs rgyas ras chen dpal grags, 1148-1218), a disciple of Dusum Khyenpa, the First Karmapa (karma pa 01 dus gsum mkhyen pa, 1110-1190). Together with a man named Nubton Tsul (snub ston tshul, d.u.) he received from him initiation in Vajravārahī. Following this he is said to have experienced numerous visions of deities. He requested permission from Sanggye Rechen to go meditate in seclusion, but was refused. Later he again planned to leave Pelgo (spel sgo), the place he where had been told by Sanggye Rechen to reside, but now a vision of Dusum Khyenpa, whom he never met, dissuaded him, telling him to settle right where he was. Accordingly Sonam Dorje remained at Pelgo for sixteen years.Sonam Dorje once asked Sanggye Rechen who would carry on his teaching. According to the Blue Annals, the elder lama replied: \" My disciples can guide themselves!Among them, I had great hopes in you and in Lodro Rinchen(blo gros rin chen, d.u.), Between you two, you will be greater in work.The labors of your disciples and those of their disciples will be great.\"After leaving Pelgo, Sonam Dorje received teachings from Tsangton Dorje Gyeltsen (gtsang ston chos rje rdo rje rgyal mtshan, 1137-1226) of Katok Monastery (kaH thog) in Kham. He later took over and renovated the monastery of Tasho Pomdrak (khra shod spom brag), which became his seat and the source of his most commonly used title. Pomdrakpa is credited with identifying the reincarnation of Dusum Khyenpa, Karma Pakshi, the Second Karmapa (karma pa 02 karma pakshi, 1204-1283). According to tradition, Pomdrakpa encountered the young boy, who, at age eleven, had received an ordination name of Chokyi Lama (chos kyi bla ma) or Chozin (chos 'dzin). (One of these names was possibly his birth name.) Pomdrakpa initially gave him lineage transmissions, including the Jinasāgara form of Avalokiteśvara, and came to believe that he was the incarnation of Dusum Khyenpa, the teacher of his own lama, Sanggye Rechen. Tradition holds that Pomdrakpa experienced a vision of Dusum Khyenpa stating that this was the case. According to the Blue Annals Pomdrakpa's death was a result of disregarding a command from Sanggye Rechen forbidding him from going to Markham (dmar khams). Having gone there, he fell ill and soon passed away."
    prediction: "",
    img: ""
  },
  {
    // https://www.druponrinpoche.org/en/lineage/kagyu-lineage/tashi-paljor-1st-sangye-nyenpa/
    firstName: "Tashi Paljor",
    aka: "",
    birth: "1457",
    death: "1525",
    lineage: "1st Sangye Nyenpa",
    work: "",
    mantra: "",
    disciple: "Mikyö Dorje",
    teacher: "Seventh Karmapa Chödrak Gyamtso",
    quote: "He then spent another five years meditating in seclusion on the Tsenmodo Island in Namtso, the largest lake in North-East Tibet. This was the same place that his Lama, Bengar Jampal Zangpo, had meditated for eighteen years, before composing the Dorje Chang Thungma.",
    contemporaries: "",
    prayer: "",
    bio: "Short bio placeholder",
    prediction: "",
    img: "./img/Tashi_Paljor.jpg"
  }
];